const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const plugins = [
	new webpack.HotModuleReplacementPlugin(),
	new HtmlWebpackPlugin({
		inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
		template: 'app/index.html',
	})
];

module.exports = require('./webpack.base')({
	mode: 'development',
	entry: [
		'webpack-hot-middleware/client?reload=true',
		path.join(process.cwd(), 'app/app.js')
	],
	output: {
		filename: '[name].js',
		chunkFilename: '[name].chunk.js',
	},
	module: {
		rules: [
			{ // Preprocess app`s css, preprocessors could be included here
				test: /\.css$/,
				exclude: /node_modules/,
				use: [
					'style-loader',
					'css-loader'
				],
			},
		]
	},
	optimisation: {
		minimize: false
	},
	plugins,
	devtool: 'eval-source-map',
});
